---
driver:
  name: vagrant

provisioner:
  # use an ansible playbook to provision our server
  name: ansible_playbook
  # name of the host
  hosts: test-kitchen
  playbook: main.yml
  # list of ansible galaxy requirements from the roles meta/main.yml
  # requirements_path: dependencies.yml
  ansible_vault_password_file: ~/vault-password-file

verifier:
  name: inspec

transport:
  max_ssh_sessions: 6

platforms:
  - name: centos-7

suites:
  # suites found at /test/integration/$test-name
  - name: default-1
    driver:
      vm_hostname: node1
      network:
      - ["private_network", {ip: "198.51.100.11"}]
  - name: default-2
    driver:
      vm_hostname: node2
      network:
      - ["private_network", {ip: "198.51.100.12"}]
